name: Sync Facades

on:
  push:
    branches:
      - main
    paths:
      - 'workers/kdco-registry/files/**'
      - 'facades/**'
      - '.github/sync.yml'
  workflow_dispatch:

jobs:
  sync:
    if: github.repository == 'kdcokenny/ocx'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Sync Files
        uses: BetaHuhn/repo-file-sync-action@8b92be3375cf1d1b0cd579af488a9255572e4619
        with:
          GH_PAT: ${{ secrets.FACADE_SYNC_PAT }}
          SKIP_PR: true
          COMMIT_EACH_FILE: false
          COMMIT_PREFIX: "sync:"
